version: '3.8'

services:
  rasa:
    build:
      context: ./services/rasa
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./services/rasa:/app
      - ./services/rasa/models:/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  actions:
    image: rasa/rasa-sdk:3.6.2
    working_dir: /app
    volumes:
      - ./services/rasa/actions:/app/actions
    command: ["rasa", "run", "actions", "-p", "5055"]
    ports:
      - "5055:5055"
    depends_on:
      - rasa

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - RASA_BASE_URL=http://rasa:5005
      - DATABASE_URL=sqlite:///data/healthbot.sqlite
    volumes:
      - ./data:/app/data
      - ./vaccines:/app/vaccines
    depends_on:
      - rasa
      - actions
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: healthbot-network
